version: '3.1'

services:
  backend:
    build: ""
    container_name: backend
    restart: "on-failure"
    ports:
      - 8000:8000
    environment:
      USE_SSL: "false"
      SERVER_ADDRESS: "0.0.0.0"
      FRONTEND_ADDRESS: "http://localhost:8443"
      PORT: "8000"
      PRODUCTION: "false"
    volumes:
      - ./src:/usr/src/app/src:ro
