version: "3.8"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile-built
      target: microservice-module-database
    container_name: ms.database
    restart: on-failure
    ports:
      - 50051:50051
  server:
    build:
      context: .
      dockerfile: Dockerfile-built
      target: microservice-module-server
    container_name: ms...server
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - database
