version: "3.4"

services:
  frontend:
    image: ${FrontendImageUrl}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DomainName: ${DomainName}
    ports:
      - "${FrontendPort}:80"
    deploy:
      mode: replicated
      replicas: 2

  backend:
    image: ${BackendImageUrl}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${BackendPort}:8000"
    deploy:
      mode: replicated
      replicas: 2
