apiVersion: v1
kind: Secret
metadata:
  name: secret-kubegres-default
  namespace: kubegres-default
type: Opaque
stringData:
  superUserPassword: X8icxianVcH24UTQ3Kp44sMaVCVKZoXYkP
  replicationUserPassword: CJLbJnXp6iWdwP7kAFfEYVqoGTKurkGeiC
