apiVersion: v1
kind: Secret
metadata:
  name: staging-ericaskari-wildcard-tls-secret-mirror
  namespace: default
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "kube-system/staging-ericaskari-wildcard-tls-secret"
